dist: focal

language: minimal

stages:
  - lint
  - deploy

if: branch = master OR type = pull_request

before_install:
  - tmpdaemon=$(mktemp)
  - sudo jq '."registry-mirrors" += ["https://mirror.gcr.io"]' /etc/docker/daemon.json > "$tmpdaemon"
  - sudo mv "$tmpdaemon" /etc/docker/daemon.json
  - sudo systemctl daemon-reload
  - sudo systemctl restart docker
  - docker system info

jobs:
  include:
    - stage: lint
      name: Project Syntax Verification
      script: make docker/run target=lint
    - stage: deploy
      if: branch = master AND type = push AND repo = plus3it/terraform-aws-tardigrade-vpc-endpoints
      before_script:
        - |
          PRIOR_VERSION=$(git describe --abbrev=0 --tags)
          RELEASE_VERSION=$(grep current_version $TRAVIS_BUILD_DIR/.bumpversion.cfg | sed 's/^.*= //' )
          RELEASE_BODY="* [terraform-aws-tardigrade-vpc-endpoints v$RELEASE_VERSION CHANGELOG](https://github.com/plus3it/terraform-aws-tardigrade-vpc-endpoints/blob/$RELEASE_VERSION/CHANGELOG.md)"
          export PRIOR_VERSION RELEASE_VERSION RELEASE_BODY
      script: skip
      before_deploy:
        - |
          (set -x; git tag -a $RELEASE_VERSION -m $RELEASE_VERSION)
      deploy:
        provider: releases
        api_key:
          secure: iq9L9QLy20Ik8BSt1giOWSJA0sPq94nyg8MsftwPEYZM6nwTa1icWVuReRJMNceuWVec2osFpDMysILX79Kli84yfCtAqD+9hjh6fXdMhGX82GcbADG7RLsiBHHOoU6IwQ3eFqw1canx+M+NqNd2vmVTuWOAA5k5ZdqKsDQnwj3aes4z9fRld0M/nMPEXGLpytDDlWgqRRNFf/WB+GFx1JDl405Fv9LAEytOVTaatD4wjTN9+DbA6NoD614PJ54EhkXhNRXJNcRdHPqlbim00dt+40nv/o2tCg589B/bdksXR1QPsxbIoe0zot8WEC2PbFfR9O0KG1nhXsRgjIJM3vkNhe+DbqF+UNvNNJE7br0n+0VEr8EnQ9ClYoxK2RFp/yzqTA5hw7+iI7j3oNKM0uO+TVUjKAQ/UfqEHhjmVDmYdGQxOit4wryb2IEIFbSU5WZBzYqKbWYGUgl9TGwCC2BCoOeNqBgUmD2Ac6cR/XTG67iOtsUrgVukzyfV1uKhzbni8Bn/pmHXE4oTNcvyef6TVFje8SHj6ok+rjcVdPR7x2XjmZkq8C/w05ZalSTuWzRYcfLg9w21y8c6N4dSCjCFPBQyz4oCj/ND2BYiEot60PJ+Ey7yBShax5qW5qvdwFKzoF9/f2KLI3tkqYjNe+YivquM9lS4FRK+Jej3JUI=
        name: $RELEASE_VERSION
        body: $RELEASE_BODY
        tag_name: $RELEASE_VERSION
        target_commitish: $TRAVIS_COMMIT
        draft: false
        on:
          branch: master
          repo: plus3it/terraform-aws-tardigrade-vpc-endpoints
          condition: '"$PRIOR_VERSION" != "$RELEASE_VERSION"'
