name: Update terraform dependencies

on:
  schedule:
    - cron:  '0 6 * * *'

jobs:
  dependabot-terraform:
    runs-on: ubuntu-latest
    steps:
      - name: update terraform dependencies
        uses: plus3it/dependabot-terraform-action@p3-implementation
        with:
          github_dependency_token: ${{ secrets.GH_READONLY_TOKEN }}
          directory: |
            /tests/config_endpoint
            /tests/custom_sg_rules
            /tests/fully_qualified_name_endpoint
            /tests/gateway_type_endpoint
            /tests/multiple_endpoints
            /tests/sg_per_endpoint
